---
cgit_url: https://bogomips.org/rainbows.git
git_url: git://bogomips.org/rainbows.git
rdoc_url: https://bogomips.org/rainbows/
merge_html:
  rainbows_1: Documentation/rainbows.1.html
  Summary: Documentation/comparison.html
public_email: rainbows-public@bogomips.org
private_email: rainbows@bogomips.org
noindex:
- TODO
- LATEST
- Unicorn
- Unicorn::Configurator
- Unicorn::SocketHelper
- EM
- Revactor
ml_url: https://bogomips.org/rainbows-public/
nntp_url:
  - nntp://news.public-inbox.org/inbox.comp.lang.ruby.rainbows
  - nntp://news.gmane.org/gmane.comp.lang.ruby.rainbows.general
