---
cgit_url: http://git.bogomips.org/cgit/rainbows.git
git_url: git://git.bogomips.org/rainbows.git
rdoc_url: http://rainbows.rubyforge.org/
changelog_start: v0.97.0
merge_html:
  rainbows_1: Documentation/rainbows.1.html
  Summary: Documentation/comparison.html
